server:
  port: 8095
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/home_app"
    username: "dev"
    password: "dev"
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changeset-master.xml
# for ubuntu need:
# 1) install nfs-common sudo apt install nfs-common
# 2) create directory (for example: sudo mkdir /mnt/nas_disk)
# 3) use mount command: sudo mount 192.168.0.12:/mnt/media/torrent /mnt/nas_disk
home-application:
  uri:
    root: "http://192.168.0.12"
  q-bit-torrent:
    port: ":10095"
    login:
      uri: "/api/v2/auth/login"
      username: "admin"
      password: "adminadmin"
    uri:
      get-all-data: "/api/v2/sync/maindata"
      delete-torrent: "/api/v2/torrents/delete"
      pause-torrent: "/api/v2/torrents/pause"
      resume-torrent: "/api/v2/torrents/resume"
      download-torrent: "/api/v2/torrents/add"
    request-timeout: 1
    torrent-category:
      root-dataset-media-path: "/torrent"
      mappings:
        '{
                    "Музыка":"/music",
                    "Видео":"/videos",
                    "Фильм":"/films",
                    "Сериал":"/serials",
                    "Игра":"/games",
                    "Программы":"/program",
                    "Операционные системы":"/os",
                    "Другое":"/other"
          }'
  meTube:
    port: ":10216"
#    downloadedPath: "\\\\192.168.0.12\\torrent"
    downloadedPath: "/mnt/nas_disk"
    quality: "best"
    uri:
      addVideoUri: "/add"

bot:
  name: "home_nas_app_bot"
  token: ""
  file-info: "https://api.telegram.org/bot{token}/getFile?file_id={fileId}"
  file-storage: "https://api.telegram.org/file/bot{token}/{filePath}"


#  psql -h localhost -d home_app -U developer -p 5432;


