server:
  port: 8096

bot:
  name: "home_nas_app_bot"
  token:
  file-info: "https://api.telegram.org/bot{token}/getFile?file_id={fileId}"
  file-storage: "https://api.telegram.org/file/bot{token}/{filePath}"

rest:
  request-timeout: 1

file:
  category: Музыка,Видео,Фильм,Сериал,Игра,Программы,Операционные системы,Другое

available-torrent-categories-list:
  channelConfigurations:
    - category: "Музыка"
      categoryFolder: "/music"
    - category: "Видео"
      categoryFolder: "/video"
    - category: "Фильм"
      categoryFolder: "/movies"
    - category: "Сериал"
      categoryFolder: "/shows"
    - category: "Игра"
      categoryFolder: "/games"
    - category: "Программы"
      categoryFolder: "/programs"
    - category: "Операционные системы"
      categoryFolder: "os"
    - category: "Другое"
      categoryFolder: "other"


#torrent:
#   -
#     category: Музыка
#     category-folder: music
#  - category: Видео
#    category-folder: video
#  - category: Фильм
#    category-folder: film
#  - category: Сериал
#    category-folder: shows




#  users:
#    -
#      username: admin
#      password: admin@10@
#      roles:
#        - READ
#        - WRITE
#        - VIEW
#        - DELETE
#    -
#      username: guest
#      password: guest@01
#      roles:
#        - VIEW

spring:
  data:
    mongodb:
      authentication-database: admin
      password: "dev"
      username: "dev"
      database: "home_app"
      port: 27017
      host: "localhost"
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: bot


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


