server:
  port: 8096

bot:
  name: "home_nas_app_bot"
  token: ""
  file-info: "https://api.telegram.org/bot{token}/getFile?file_id={fileId}"
  file-storage: "https://api.telegram.org/file/bot{token}/{filePath}"

rest:
  request-timeout: 1

file:
  category: Музыка,Видео,Фильм,Сериал,Игра,Программы,Операционные системы,Другое

spring:
  data:
    mongodb:
      authentication-database: admin
      password: "dev"
      username: "dev"
      database: "home_app"
      port: 27017
      host: "localhost"
      auto-index-creation: false


